# Setup
title:               wwwBase
tagline:             'Github page and blog starter'
description:         'What i(and you= need to start a new github page.'
url:                 https://mumma.nu/wwwBase
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Patrik Gustafsson
  url:               https://twitter.com/paven
  email:             wwwBase@mumma.nu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
