# Dependencies
markdown:         redcarpet
highlighter:      pygments

kramdown:
  input: GFM

# Setup
title:               wwwBase
tagline:             'Github page and blog starter'
description:         'What i(and you= need to start a new github page.'
url:                 https://mumma.nu/wwwBase
baseurl:             ''
paginate:            5
permalink:           pretty
paginate_path:    "blog/page:num"
banner:           banner.jpg

# About/contact
author:
  name:              Patrik Gustafsson
  url:               https://twitter.com/paven
  email:             wwwBase@mumma.nu

# Custom vars
version:          1.1.0
google_analytics_id: #UA-XXXX-Y

github:
  repo:           https://github.com/paven/wwwBase

gems:
- jekyll-mentions
- jekyll-sitemap

first_page:
  url: /index/

